### ISSUE TITLE
[All]sass颜色变量计算方法按照固定格式使用

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1029]
## 背景
https://github.com/alibaba/ice/issues/2715

## 方案
组件需要正常使用sass的颜色计算能力，为配合ice工程上的在线主题切换功能实现，针对 Next 组件进行约束方便统一提取计算变量：

- 所有计算变量均需要定义在 variable.scss 文件中
- 按指定的命名规则由工程获取，参与颜色计算的 均需要以 $color-calculate 开头

for example:
````scss
// src/search/scss/variable.scss
// you can only define the scss variable in variable.scss
$color-calculate-search-normal-dark-bg: transparentize($search-normal-dark-bg-color, 1 - $search-normal-dark-bg-opacity) !default;

// src/search/main.scss
.#{$css-prefix}select {
    background: $color-calculate-search-normal-dark-bg;
}
````
