### ISSUE TITLE
Remove the last margin of the form item

### ISSUE THREAD

**Issue by no-repeat** [alibaba-fusion/next#105]
**Is your feature request related to a problem? Please describe.**
The last margin affects the style. When I use Form with Dialog, there are too much spacing.

**Describe the solution you'd like**
Remove the margin.

![image](https://user-images.githubusercontent.com/6202845/50321205-b2dab400-050a-11e9-986b-e25296bc3b80.png)

**Comment by youluna** [comment]
This change may cause incompatibilities, we decided not to change it.
You can 
```css
.next-form .next-form-item:last-of-type { 
    margin-bottom: 0;
}
```
