### ISSUE TITLE
[Tag]支持多颜色配置

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#1212]
### Component 
Tag
### Feature Description
现有tag在交互功能上区分较多，但是样式上比较单一，无法满足多种状态的tag需求，需要进行功能补全。

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/qBbKTmGNHsuH.png)

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/hnsDeIKa6t7Q.png)

**Comment by youluna** [comment]
建议新增API  color，预设几个颜色值，例如 red  green blue yellow等。
增加不可配置的variable.scss变量组
```scss
$tag-colorful-red-text-color: #ddd;
$tag-colorful-red-bg-color: #ddd; 
$tag-colorful-red-border-color: #ddd; 

```

<Tag color="red" />默认是
```scss
...
  &-red {
    color: $tag-colorful-red-text-color;
    border-color: $tag-colorful-red-border-color;
    background-color: $tag-colorful-red-bg-color;
}
...
```
<Tag color="red-reverse" />默认是
```scss
...
  &-red {
    color: $color-white
    border-color: $tag-colorful-red-text-color;
    background-color: $tag-colorful-red-text-color;
}
...
```
