### ISSUE TITLE
能否把Table.Column中的align设置分为headerAlign和align

### ISSUE THREAD

**Issue by dieslrae** [alibaba-fusion/next#197]
在很多时候项目要求表头居中,但是内容文本居左数字居右,现在表头和内容是共用的align,无法分开设置

**Comment by youluna** [comment]
可以通过重写样式实现
```jsx
 <Table.Column title="Id" dataIndex="id"  align={'left'}/>
```
```css
.next-table-header {
    text-align: right
}
```
