### ISSUE TITLE
[Search]编译报错

### ISSUE THREAD

**Issue by jerryyxu** [alibaba-fusion/next#1999]
### 样式的calc方法导致业务工程构建报错问题

一开始是为了处理sass中，px与百分比值进行计算导致的编译报错：

![image](https://user-images.githubusercontent.com/8581684/87622637-216b0c80-c756-11ea-9296-13e19362797f.png)

解决方式是使用calc函数，不过在sass中，calc函数中如果有sass变量，需要特殊处理：https://sass-lang.com/documentation/syntax/special-functions#calc-element-progid-and-expression
否则sass编译之后的会保留变量，**但是并不报错**，只是生成的样式无效。
```scss
.logo {
  $width: 800px;
  width: $width;
  position: absolute;
  // left: calc(50% - $width); 编译之后：calc(50% - $width)
  left: calc(50% - #{$width}); // 编译之后：calc(50% - 800px)
  top: 0;
}
```
业务方的工程在构建时报错是因为使用[postcss-calc](https://github.com/postcss/postcss-calc)插件，该插件会计算calc中的一些变量，所以会检测出非法的sass变量值。

![image](https://user-images.githubusercontent.com/8581684/87623260-9a1e9880-c757-11ea-8a2d-d8a5e4876227.png)
![image](https://user-images.githubusercontent.com/8581684/87623822-dc94a500-c758-11ea-9787-54c7d93dc9b1.png)

**Comment by youluna** [comment]
### 影响面
使用了post-css插件的，正在本地开发的用户

### 解决措施
在本地开发环境，启用postcss-calc插件，进行严格检查，把不合法的写法提前识别出来

**Comment by bindoon** [comment]
后续对 calc 写法有啥要求吗，我怎么知道什么写法不合法呢

**Comment by youluna** [comment]
scss文件中写calc()  var()等css函数，函数中的变量值需要带着#{}修饰，也就是说原来的写法是
```scss
$width: 50% + $border;
```
改成calc形式应该是
```scss
// right
$width: calc(50% + #{$border});
// wrong
$width: calc(50% + $border);
```
假如$border是 2px，他们分别会被编译成
```scss
// right 确切值
$width: calc(50% + 2px});
// wrong 字符串
$width: calc(50% + $border);
```

其中错误写法是可以通过sass编译的，不过会被postcss-calc拦住，它更严格，所以我们在开发环境也引入了这个严格的插件，这样在开发阶段错误的写法会直接报错，抛出给开发者，从而避免这个问题
