### ISSUE TITLE
[Table] lock开启时，Column错位

### ISSUE THREAD

**Issue by cwtuan** [alibaba-fusion/next#2003]
### Component 
Table

### Steps to reproduce
[reproduce link](https://riddle.alibaba-inc.com/riddles/a6004c3a)
Column底下有个Button时，就会造成错位
```jsx
<Table.Column 
 lock='left'
 width="100px" 
 dataIndex="title.name" 
 cell={(v)=><Button text>{v}</Button>} 
/>
```
  
![image](https://user-images.githubusercontent.com/3455798/87670006-97489580-c7a1-11ea-97b8-6faa6afb35d0.png)

**Comment by youluna** [comment]
TableCell的内容如果有设置white-space: nowrap; 是会破坏table的布局的，Button组件默认是不折行的，比较快的解决办法是把<Button />换成<a />

**Comment by cwtuan** [comment]
改用a后，还需要将文字比较长的时候，显示成  点点点 符号，这样又破坏了
```css
.ellipsis {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```
