### ISSUE TITLE
[Input]Form 里 Input 组件在 Chrome 和 Safari 自动载入填写记录的时候，会出现样式 Bug

### ISSUE THREAD

**Issue by Crayon-ShinChan** [alibaba-fusion/next#2017]
### Component 
Input

### Reproduction link 
[https://github.com/Crayon-ShinChan/elezoo-iceapp](https://github.com/Crayon-ShinChan/elezoo-iceapp)

### Steps to reproduce
我在我的应用 https://github.com/Crayon-ShinChan/elezoo-iceapp 的登陆页面 `localhost:3333/#/user/login`，登陆过一次后，chrome 应该是记住了账号密码， **再次进入这个登陆页面的时候，chrome 自动填写了账号密码，Form 里面 Input 页面样式出现Bug，圆角的地方被白色覆盖，** 错误样式如下：

![image](https://user-images.githubusercontent.com/38809606/88274506-67077680-cd0e-11ea-9b91-2df7780676cf.png)

如果删除 chrome 自动填写的信息，并且自己手动填入 Input 信息，会回归正常样式，正常样式如下：

![image](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/dRNgHDMAwOIO.png)

可以用我上面提供的 icejs 的仓库直接复现问题（删除一下后端的 request 请求的代码，防止请求错误）。

请问这个 Bug 的原因是什么呢？有快速的解决办法吗？

**Comment by Crayon-ShinChan** [comment]
我今天做了个测试。
测试浏览器：Safari + Chrome
测试主题包：官方的三款主题包 theme-1、theme-2 和 theme-4

发现所有的主题包下面的 Input 组件在 Safari 和 Chrome 下均会出现 Input 组件边角消失的 Bug。（当我们使用浏览器之前记录的账号密码进行自动填充之后）

theme-1:
![image](https://user-images.githubusercontent.com/38809606/88274172-daf54f00-cd0d-11ea-8b90-f256c93eea65.png)
theme-2:
![image](https://user-images.githubusercontent.com/38809606/88274197-e3e62080-cd0d-11ea-8d28-e6119f5a07fc.png)
theme-4:
![image](https://user-images.githubusercontent.com/38809606/88274215-e9dc0180-cd0d-11ea-9bb0-7c2055c77d8d.png)

上面的几张图可见，圆角越大的 input 出现这个 bug 越明显，特别是官方的 theme-1 和 theme-4，完全破坏了它们的设计。

Input 这个组件实在是太常用了，跪求解决呀！

**Comment by Crayon-ShinChan** [comment]
问题原因：浏览器 autofill 的时候会给 input 里面加入新样式，这个样式的背景是白色的，这会覆盖掉原来的透明背景样式：
![image](https://user-images.githubusercontent.com/38809606/88306297-2410c780-cd3d-11ea-8377-2073b8c6e5f5.png)

临时解决方案：
google 了很多代码都没办法让背景变成透明，所以只能强行把 autofill 时的 input 的 `border-radius` 改掉，加上圆角，来避免覆盖 Input 组件的圆角边框，代码如下：
```scss
// src/global.scss
// 引入默认全局样式
@import '~@alifd/next/variables.scss';

input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
input:-webkit-autofill:active {
  border-radius: $corner-3;
}
```

还是希望 fusion design 能够主动支持解决这个问题（如果有可行方案的话）。
