### ISSUE TITLE
[Step]balloon内使用step，动画异常

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2414]
### Component 
Step

### Reproduction link 
https://riddle.alibaba-inc.com/riddles/f93efd36

### Steps to reproduce
@alifd/next@1.12.3  // Balloon动画正常、Step`shape="circle"`时不支持`direction="ver" `
@alifd/next@1.12.4  // Balloon动画正常、Step`shape="circle"`时不支持`direction="ver" `
@alifd/next@1.17.1  // Balloon动画异常、Step`shape="circle"`时支持`direction="ver" `，但是宽度不对

发现有两个问题：
1.  1.17.1 动画异常，Balloon展开的动画不顺滑
      -  经过排查是 https://github.com/alibaba-fusion/next/commit/f4535d3 修改了动画时常，跟Balloon搭配起来有问题。将icon的动画时常设置为大于300ms可以解决
```css
.next-step-item-node-circle .next-icon {
  animation: zoomIn 300ms linear!important;
}
```
2.  1.12.4开始，虽然Step的circle模式，支持了`direction=“ver”`，但是宽度设置异常：
![image](https://user-images.githubusercontent.com/10049465/99903510-e67a7600-2cff-11eb-957a-59479c24a58a.png)
