### ISSUE TITLE
[MenuButton]Unexpected arrow color on secondary MenuButton when hovered

### ISSUE THREAD

**Issue by luhaopeng** [alibaba-fusion/next#2603]
### Component 
MenuButton

### Reproduction link 
[https://codepen.io/luhaopeng/pen/mdrKpQr](https://codepen.io/luhaopeng/pen/mdrKpQr)

### Steps to reproduce
open link above

### Unexpected behavior
![unexpected.jpg](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/M6J42OtcysBt.png)

### Expected behavior
![expected.jpg](https://fusion-image.oss-cn-beijing.aliyuncs.com/images/dY9Y2YeRfMrr.png)

### Possible problem
```css
.next-btn.next-btn-secondary:focus, .next-btn.next-btn-secondary:hover, .next-btn.next-btn-secondary.hover {
  color: #FFFFFF;
  /* ... */
}
```
has lower priority than
```css
.next-menu-btn.next-btn-secondary .next-menu-btn-arrow {
  color: #034cfa;
}
```
