### ISSUE TITLE
[Drawer]close icon不随内容滚动

### ISSUE THREAD

**Issue by luhaopeng** [alibaba-fusion/next#2842]
### Component 
Drawer

### Reproduction link 
[https://codepen.io/luhaopeng/pen/zYNKggx](https://codepen.io/luhaopeng/pen/zYNKggx)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/13071103/112969750-21922780-9180-11eb-9b5a-33f32b64e8e2.png)
如图，drawer内容过长滚动时，close icon不随内容滚动。

### 解决方式
为header添加`position: relative`
```css
.next-drawer-header {
  position: relative;
}
```
