### ISSUE TITLE
[Switch]增加autoWidth api，让用户手动开启自动间距

### ISSUE THREAD

**Issue by youluna** [alibaba-fusion/next#2993]
### Component 
Switch
### Feature Description
对于 `<Switch style={{display: 'block'}}>`  写法的用户，开启autoWidth前后样式不一致，如：
![image](https://user-images.githubusercontent.com/10049465/118216930-fdc44000-b4a6-11eb-9619-e65e76ceb04c.png)
原因是默认情况下：
```css
.next-switch {
    width: $switch-s-width;
}
```

开启 autoWidth 情况下设置了:
```css
.next-switch {
    width: auto;
    min-width: $switch-s-width;
}
```
