### ISSUE TITLE
[Breadcrumb]面包屑的高度不应该固定

### ISSUE THREAD

**Issue by bindoon** [alibaba-fusion/next#3111]
### Component 
Breadcrumb

### Steps to reproduce
原来默认主题
```css
.next-breadcrumb-text {
  height: 16px; /* =$s-4 */
  font-size: 14px; 
  line-height: 16px;  /* =height */
}
```
在千牛主题中，$s-base=3
```css
.next-breadcrumb-text {
  height: 12px; /* =$s-4 */
  font-size: 14px; 
  line-height: 12px;  /* =height */
}}
```
![image](https://user-images.githubusercontent.com/5189853/122231729-3e233d80-ceed-11eb-8726-b0f944d413c7.png)

line-height 规则应该满足： font-size <= line-height <= height
