### ISSUE TITLE
css variable与design token的映射支持

### ISSUE THREAD

**Issue by cccRaim** [alibaba-fusion/next#3350]
### Type 
Platform Theme

### Feature Description
目前Fusion的主题发布后，可以使用index.var.scss直接进行css variables的替换。
但是有一个问题是，想要动态更改颜色的时候，需要更改所有相关的变量
比如按钮的颜色
```scss
$btn-pure-primary-bg: var(--btn-pure-primary-bg, #0066ff);
$btn-pure-secondary-border-color: var(--btn-pure-secondary-border-color, #0066ff);
```

这两个都是#0066ff，都引用了『Brand-1-6』，但是假如要改的话，只能同时改这两个css变量，无法通过更改--color-brand1-6实现，缺少组件样式和颜色的关系。
想问一下能不能进行优化呢？建议改成以下的形式
```scss
$color-brand1-6: var(--color-brand1-6, #0066ff);
$btn-pure-primary-bg: var(--color-brand1-6, #0066ff);
$btn-pure-secondary-border-color: var(--color-brand1-6 #0066ff);
```
或者
```scss
:root {
  --btn-pure-primary-bg: var(--color-brand1-6, #0066ff);
  --btn-pure-secondary-border-color: var(--color-brand1-6, #0066ff);
}
$btn-pure-primary-bg: var(--btn-pure-primary-bg, #0066ff);
$btn-pure-secondary-border-color: var(--btn-pure-secondary-border-color, #0066ff);
```
