### ISSUE TITLE
[Select]Select的showSearch模式会造成布局抖动

### ISSUE THREAD

**Issue by csr632** [alibaba-fusion/next#3781]
### Component 
Select

### Reproduction link 
[https://riddle.alibaba-inc.com/riddles/55eb684d](https://riddle.alibaba-inc.com/riddles/55eb684d)

### Steps to reproduce

左边的Select打开下拉框时，它的宽度会变大，将右边的内容会向右推，导致布局抖动

### 原因分析

![image](https://user-images.githubusercontent.com/18747423/157200666-bbf2236f-48d9-4049-8d72-71b3966b13d6.png)
这里多了个空格，导致focus的时候，`.next-select-trigger-search`的宽度变大了。
代码位置：https://github.com/alibaba-fusion/next/blob/420cb22cb1c82d0c1a9b20c4165975e7e3840cea/src/select/select.jsx#L1096

这行代码似乎在刚开源时就存在了，能删掉吗：https://github.com/alibaba-fusion/next/blob/aa8f47bd931fad0a3e1941327ac3f180d3937680/src/select/select.jsx#L751

**Comment by bindoon** [comment]
好像删掉还是变大

**Comment by csr632** [comment]
将这个`nbsp`改成1px的宽度，能够恰好让总体宽度保持不变：
```css
.next-select-trigger-search > span > span:last-child {
  display: inline-block;
  width: 1px;
}
```
@bindoon 
https://riddle.alibaba-inc.com/riddles/7d22b6e5
